<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net9.0-windows</TargetFramework>
	  <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
    <RootNamespace>Node_Plugin</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\External Langauage Manager\External Langauage Manager.csproj" />
  </ItemGroup>

</Project>
