<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>bin\Debug\net9.0-windows\icon1.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net9.0-windows\icon1.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="LibGit2Sharp.NativeBinaries" Version="2.0.323" />
    <PackageReference Include="Meziantou.Framework.Win32.CredentialManager" Version="2.0.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\External Langauage Manager\External Langauage Manager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
